/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cartographer_jni_CartographerJniJavaBridge */

#ifndef _Included_cartographer_jni_CartographerJniJavaBridge
#define _Included_cartographer_jni_CartographerJniJavaBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cartographer_jni_CartographerJniJavaBridge
 * Method:    startCartographer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cartographer_jni_CartographerJniJavaBridge_startCartographer
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cartographer_jni_CartographerJniJavaBridge
 * Method:    sendOdometryData
 * Signature: (Ljava/lang/String;J[F)V
 */
JNIEXPORT void JNICALL Java_cartographer_jni_CartographerJniJavaBridge_sendOdometryData
  (JNIEnv *, jobject, jstring, jlong, jfloatArray);

/*
 * Class:     cartographer_jni_CartographerJniJavaBridge
 * Method:    sendLaserScanData
 * Signature: (Ljava/lang/String;J[F)V
 */
JNIEXPORT void JNICALL Java_cartographer_jni_CartographerJniJavaBridge_sendLaserScanData
  (JNIEnv *, jobject, jstring, jlong, jfloatArray);

/*
 * Class:     cartographer_jni_CartographerJniJavaBridge
 * Method:    finalizeCartographer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cartographer_jni_CartographerJniJavaBridge_finalizeCartographer
  (JNIEnv *, jobject);

/*
 * Class:     cartographer_jni_CartographerJniJavaBridge
 * Method:    getGridMap
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_cartographer_jni_CartographerJniJavaBridge_getGridMap
  (JNIEnv *, jobject);

/*
 * Class:     cartographer_jni_CartographerJniJavaBridge
 * Method:    getCurrentPose
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_cartographer_jni_CartographerJniJavaBridge_getCurrentPose
  (JNIEnv *, jobject);

/*
 * Class:     cartographer_jni_CartographerJniJavaBridge
 * Method:    addSensor
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cartographer_jni_CartographerJniJavaBridge_addSensor
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
